apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        envFrom:
          - configMapRef:
              name: cm-mysql
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql
data:
  MYSQL_ROOT_PASSWORD: secret-pw
  MYSQL_DATABASE: indus_db

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
