spring:
  application:
    name: expense_manager
  datasource:
    url: jdbc:mysql://localhost:3306/indus_db
    username: root
    password: secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8090