apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-manager
spec:
  selector:
    matchLabels:
      app: expense-manager
  template:
    metadata:
      labels:
        app: expense-manager
    spec:
      containers:
      - name: expense-manager
        image: IMAGE
        imagePullPolicy: Always
        env:
          - name: username
            value: root
        envFrom:
          - configMapRef:
              name: service-discovery
          - secretRef:
              name: db-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: expense-manager-service
spec:
  selector:
    app: expense-manager
  ports:
  - port: 8080
    targetPort: 8080
