on: 
  workflow_call: 
    inputs:
      context:
        type: string
        required: true
      image_tag: 
        type: string
        required: true
    secrets:
      docker_password:
        required: true
      service_account_json:
        required: true

jobs:
  docker_build:
    runs-on: ubuntu-22.04
    name: <>
    steps:
      - name: checkout
        uses: actions/checkout@v4    

      - name: GCP Registry Login
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key_base64
          password: ${{secrets.docker_password}}

      - name: Docker Build and Push 
        uses: docker/build-push-action@v6
        with:
          context: ${{github.workspace}}/${{inputs.context}}
          push: true
          tags: "${{inputs.image_tag}}"

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
      
      - name: gke auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.service_account_json }}'

      - name: set kubeconfig
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'indus-dev-cluster'
          location: 'us-central1-b'
      
      - name : Deploy to GKE
        working-directory: ${{github.workspace}}
        run: |
          sed -i 's\IMAGE\${{inputs.image_tag}}\' ./${{inputs.context}}/kube.yaml
          kubectl apply -f ./${{inputs.context}}/kube.yaml


  
