on: 
  workflow_call: 
    inputs:
      context:
        type: string
        required: true
      image_tag: 
        type: string
        required: true
    secrets:
      docker_password:
        required: true

jobs:
  docker_build:
    runs-on: ubuntu-22.04
    steps:

      - name: checkout
        uses: actions/checkout@v4    

      - name: GCP Registry Login
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key_base64
          password: ${{secrets.docker_password}}

      - name: Docker Build and Push 
        uses: docker/build-push-action@v6
        with:
          context: ${{github.workspace}}/${{inputs.context}}
          push: true
          tags: "${{inputs.image_tag}}"
  
  # Deployment_GKE:
  #   needs: docker_build
  #   name: Deploy to GKE
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - name: Install Kubectl
  #       uses: azure/setup-kubectl@v3
      
  #     - name: gke auth
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         credentials_json: '${{ secrets.GKE_SERVICE_ACCOUNT_JSON }}'

  #     - name: set kubeconfig
  #       uses: 'google-github-actions/get-gke-credentials@v2'
  #       with:
  #         cluster_name: 'indus-dev-cluster'
  #         location: 'us-central1-b'
      
  #     - name : Deploy to GKE
  #       working-directory: ${{github.workspace}}
  #       run: |
  #         sed -i 's\IMAGE\${{env.Image_tag}}\' ./api_gateway/kube.yaml
  #         kubectl apply -f ./api_gateway/kube.yaml


  
