on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
        inputs:
            version:
                default: v1

run-name: Trigger CI/CD

jobs:
    trigger:
        name: Filter Changes
        runs-on: ubuntu-22.04
        outputs:
            changes: ${{steps.filter.outputs.changes}}
        steps:
            - name: checkout
              uses: actions/checkout@v4       
                   
            - name: checking directory changes
              uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                    api_gateway:
                        - api_gateway/**
                    ic-auth-service:
                        - ic-auth-service/**
                    expense_manager:
                        - expense_manager/**
    build_deploy:
        if: needs.trigger.outputs.changes != '[]'        
        uses: ./.github/workflows/Build_Deploy.yml
        with:
            Image_tag: "${{vars.DOCKER_IMAGE_PREFIX_GCP}}/${{matrix.service}}:${{ github.run_number }}"
            context: ${{matrix.service}} 
        secrets: 
            docker_password: ${{secrets.DOCKER_PUSH_GCP}}
            service_account_json: ${{secrets.GKE_SERVICE_ACCOUNT_JSON}}
        needs: trigger
        name: Build_Deploy 
        strategy:
            matrix:
                service: ${{ fromJSON(needs.trigger.outputs.changes) }}



            