on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
        inputs:
            version:
                default: v1

run-name: Trigger CI/CD

jobs:
    trigger:
        name: Filter Changes
        runs-on: ubuntu-22.04
        outputs:
            changes: ${{steps.filter.outputs}}
        steps:
            - name: checkout
              uses: actions/checkout@v4       
                   
            - name: checking directory changes
              uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                    api_gateway:
                        - api_gateway/**
                    auth_service:
                        - ic-auth-service/**
    build_deploy:
        needs: trigger
        name: Build_Deploy Services
        # if: fromJSON(needs.trigger.outputs.changes) == 
        # strategy:
        #     matrix:
        #         service: ${{ fromJSON(needs.trigger.outputs.changes) }}
        runs-on: ubuntu-22.04
        steps:
            - run: echo ${{needs.trigger.outputs.changes}}

    api_gateway_build_deploy:
        name: Build_Deploy api_gateway
        needs: trigger
        if: needs.trigger.steps.changes.outputs.api_gateway == 'true'
        uses: ./.github/workflows/Build_Deploy.yml
        with:
            Image_tag: "${{vars.DOCKER_IMAGE_PREFIX_GCP}}/api_gateway:${{ github.run_number }}"
            context: api_gateway

    # auth_service_build_deploy:
    #     name:  Build_Deploy auth_service
    #     needs: trigger
    #     if: needs.trigger.steps.changes.outputs.expense_manager == 'true'
    #     uses: ./.github/workflows/Build_Deploy.yml
    #     with:
    #         Image_tag: "${{vars.DOCKER_IMAGE_PREFIX_GCP}}/auth_service:${{ github.run_number }}"
    #         context: ic-auth-service
            